[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/mark-it-done"
  to = "https://mark-it-done-600.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/mark-it-done/*"
  to = "https://mark-it-done-600.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/scannow/*"
  to = "https://scannow-100.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/scannow"
  to = "/scannow/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
